CHANGELOG.md, package.json, packages/monaco-editor/monaco-editor-base.component.ts, packages/monaco-editor/monaco-editor-diff.component.ts, packages/monaco-editor/monaco-editor.component.ts, packages/monaco-editor/monaco-editor.types.ts, src/app/core/code/code.service.ts, src/app/routes/demo.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(9.1.1): release 9.1.1

packages/util/README.md, packages/util/convert/convert.spec.ts, packages/util/convert/convert.ts, packages/util/convert/index.ts, packages/util/convert/package.json, packages/util/convert/public-api.ts, packages/util/ng-package.json, packages/util/package.json, packages/util/tsconfig.lib.json, packages/util/util.ts, scripts/ci/build.sh
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
=> feat: add util libary

packages/lazy/package.json, packages/monaco-editor/README.md, packages/monaco-editor/monaco-editor-base.component.ts, packages/monaco-editor/monaco-editor.component.ts, packages/monaco-editor/package.json
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(monaco-editor): add `delay` property

CHANGELOG.md, README.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(9.2.0): release 9.2.0

CHANGELOG.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(10.0.0): release 10.0.0

CHANGELOG.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(10.1.0): release 10.1.0

packages/markdown/ng-package.json, packages/markdown/package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(module:markdown): fix missing dependencies

CHANGELOG.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(10.1.1): release 10.1.1

packages/markdown/markdown.service.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(module:markdown): fix unable to load again

packages/lazy/README.md, packages/lazy/lazy.service.spec.ts, packages/lazy/lazy.service.ts, packages/markdown/markdown.service.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(module:lazy): use `monitor` instead `change`

CHANGELOG.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(10.2.0): release 10.2.0

CHANGELOG.md, package.json, packages/monaco-editor/monaco-editor-base.component.ts, packages/monaco-editor/monaco-editor.module.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(10.2.2): release 10.2.2

CHANGELOG.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(11.0.0): release 11.0.0

packages/markdown/README.md, packages/markdown/markdown-base.component.ts, packages/markdown/markdown-preview.component.ts, packages/markdown/markdown.component.ts, packages/markdown/markdown.module.ts, src/app/routes/home/home.component.html, src/app/routes/home/home.component.ts, tslint.json
- close #22
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(module:markdown): add `nu-markdown-preview` component

CHANGELOG.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(11.1.0): release 11.1.0

packages/lazy/lazy.service.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: remove deprecated

scripts/ci/build.sh
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix: fix losing `monaco.d.ts`

CHANGELOG.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(11.1.1): release 11.1.1

packages/lazy/README.md, packages/lazy/lazy.service.spec.ts, packages/lazy/lazy.service.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(module:lazy): allow to specify resource type

CHANGELOG.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(11.2.0): release 11.2.0

packages/monaco-editor/monaco-editor-diff.component.ts, packages/monaco-editor/monaco-editor.component.ts
- close #34
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix: fix invalid disabled in init

CHANGELOG.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(12.0.0): release 12.0.0

packages/monaco-editor/monaco-editor-base.component.ts, packages/monaco-editor/monaco-editor.config.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(module:monaco): add monacoPreLoad Config

CHANGELOG.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(12.1.0): release 12.1.0

packages/tsconfig.lib.prod.json
- close #42
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix: should be close  ivy of npm package

CHANGELOG.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(12.1.1): release 12.1.1

CHANGELOG.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(12.1.2): release 12.1.2

CHANGELOG.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(13.0.0): release 13.0.0

CHANGELOG.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(13.1.0): release 13.1.0

CHANGELOG.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(14.0.0): release 14.0.0

packages/markdown/markdown-preview.component.ts
- [ x] The commit message follows our guidelines: https://github.com/ng-util/ng-util/blob/master/CONTRIBUTING.md#commit
- [x ] Tests for the changes have been added (for bug fixes / features)
- [x ] Docs have been added / updated (for bug fixes / features)
```
[ x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x ] No
```
=> fix(markdown): add options to preview

CHANGELOG.md, package.json, packages/markdown/public-api.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(14.0.1): release 14.0.1

CHANGELOG.md, scripts/publish/publish.sh
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(15.0.0): release 15.0.0

CHANGELOG.md, package.json, scripts/publish/publish.sh
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(16.0.0): release 16.0.0

CHANGELOG.md, package.json, scripts/publish/package.json, scripts/publish/publish.js, scripts/publish/publish.sh
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(16.0.1): release 16.0.1

CHANGELOG.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(17.0.0): release 17.0.0

packages/markdown/README.md, packages/markdown/markdown.config.ts, packages/markdown/markdown.module.ts, packages/monaco-editor/README.md, packages/monaco-editor/monaco-editor.config.ts, packages/monaco-editor/monaco-editor.module.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat: use `provide` instead of `forRoot`

CHANGELOG.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(17.0.1): release 17.0.1

CHANGELOG.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(18.0.0): release 18.0.0

CHANGELOG.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(18.1.0): release 18.1.0

CHANGELOG.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(19.0.0): release 19.0.0

packages/monaco-editor/monaco-editor.component.ts, src/app/routes/_monaco.ts, src/index.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(monaco-editor): fix can't auto format when `ngModel` changed

CHANGELOG.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(20.0.1): release 20.0.1

CHANGELOG.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(20.0.2): release 20.0.2

CHANGELOG.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(20.1.0): release 20.1.0
